// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoWToken.Server.Data.Models;

namespace WoWToken.Server.Data.Migrations
{
    [DbContext(typeof(WoWTokenContext))]
    partial class WoWTokenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WoWToken.Server.Data.Models.Database.WoWToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("LastUpdatedTimestamp")
                        .HasColumnName("LastUpdatedTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("Price")
                        .HasColumnName("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("Region")
                        .HasColumnName("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WoWToken","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
